[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }  # Change to your preferred font
size = 14  # Adjust as needed
[env]
TERM = "xterm-256color"
[window]
title = "Terminal" # Alacritty
dynamic_title = false

[general]
import = ["/home/sonu/.config/alacritty/catppuccin/catppuccin-mocha.toml"]  # Change to latte, frappe, or macchiato if preferred

[terminal] 
shell = { program = "/usr/bin/nu", args = [] }
