host := "knull" 

update:
    nix flake update
switch:
    home-manager switch --flake .#{{host}}
switch-backup:
    home-manager switch --flake .#{{host}} -b backup
clean:
    nix-collect-garbage -d
