[colors.primary]
background = "#090a0f"
foreground = "#d2e2ee"

[colors.normal]
black = "#090a0f"
red = "#4A6F9C"
green = "#5E8BB6"
yellow = "#3EA5C2"
blue = "#719DCB"
magenta = "#8AB5DA"
cyan = "#9AC4E4"
white = "#d2e2ee"

[colors.bright]
black = "#939ea6"
red = "#4A6F9C"
green = "#5E8BB6"
yellow = "#3EA5C2"
blue = "#719DCB"
magenta = "#8AB5DA"
cyan = "#9AC4E4"
white = "#d2e2ee"
