[colors.primary]
background = "#0D1216"
foreground = "#d2d9dd"

[colors.normal]
black = "#0D1216"
red = "#73986B"
green = "#3E6880"
yellow = "#517688"
blue = "#7096AA"
magenta = "#7DA7C5"
cyan = "#8AB4D3"
white = "#d2d9dd"

[colors.bright]
black = "#93979a"
red = "#73986B"
green = "#3E6880"
yellow = "#517688"
blue = "#7096AA"
magenta = "#7DA7C5"
cyan = "#8AB4D3"
white = "#d2d9dd"
