[language-server.hx-lsp]
command = "hx-lsp"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "nix"
language-servers = ["nixd","hx-lsp","harper-ls"]
auto-format = true
formatter = { command = "alejandra" }

[[language]]
name = "python"
language-servers = ["basedpyright" , "ruff","hx-lsp","harper-ls"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "rust"
language-servers = ["rust-analyzer","hx-lsp","harper-ls"]
formatter = { command = "rustfmt" }
[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "go"
language-servers = ["gopls","golangci-lint","hx-lsp","harper-ls"]
formatter = { command = "goimports" }
auto-format = true

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci" ]}
language-servers = ["bash-language-server","shellcheck","hx-lsp","harper-ls"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "markdown"
language-servers = ["hx-lsp","harper-ls"]
