[[language]]
name = "nix"
language-servers = ["nixd"]
auto-format = true
formatter = { command = "alejandra" }

[[language]]
name = "python"
language-servers = ["basedpyright" , "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "go"
language-servers = ["gopls","golangci-lint"]
formatter = { command = "goimports" }

[[language]]
name = "go"
auto-format = true

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci" ]}
language-servers = ["bash-language-server","shellcheck"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]
