set -ga terminal-overrides ",tmux-256color:Tc"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-kitty:Tc"

set -g window-style 'bg=default'
set -g window-active-style 'bg=default'


##### Keybindings #####
bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R

##### General #####
set -g mouse on
set -g history-limit 5000
set -g default-shell "/home/sonu/.nix-profile/bin/fish"

# Proper truecolor + transparency passthrough
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",tmux-256color:Tc"

# Do NOT draw tmux backgrounds
set -g pane-border-style bg=default
set -g pane-active-border-style bg=default
set -g status-style bg=default

##### Reload #####
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

##### TPM #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

##### Catppuccin #####

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_transparent_background "true"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_active_fill "none"

run ~/dotfiles/tmux/plugins/catppuccin/tmux/catppuccin.tmux

##### Status Line #####
set -g status-left ""
set -g status-left-length 0
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"

run ~/dotfiles/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/dotfiles/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux

run-shell "tmux set -g status-style bg=default"

##### TPM init (MUST BE LAST) #####
run '~/.tmux/plugins/tpm/tpm'

