[shell.files] 
"shell" = "~" 

[tmux.files] 
"tmux" = { target = "~/.config/tmux", type = "symbolic", recurse = false}

[alacritty.files] 
"alacritty" = {target = "~/.config/alacritty", type = "symbolic" , recurse = false}

[nvim.files] 
"nvim" = {target = "~/.config/nvim", type = "symbolic" , recurse = false} 


[starship.files] 
"starship" = "~/.config" 

[myscripts.files] 
"myscripts/code_runner.sh" = "~/.local/bin/run"
"myscripts/copy_clip.sh" = "~/.local/bin/copy" 
"myscripts/vmux.sh" = "~/.local/bin/vmux"
"myscripts/postrun" = "~/.local/bin/syncwal"
"myscripts/connect.sh" = "~/.local/bin/connect"

[nushell.files]
"nushell" = {target = "~/.config/nushell", type = "symbolic" , recurse = false}
